In [2]:
import numpy as np

In [ ]:
arr1=np.array([5,3,4])
arr2=np.array([1,2,3])

In [ ]:
arr1*arr2

In [ ]:
pro=np.dot(arr1,arr2)
print(pro)

In [ ]:
help(sum)


In [ ]:
print(arr1.sum())

In [ ]:
arr1.shape

In [ ]:
arr1

In [ ]:
arr3=np.array([[2,3],
               [2,3]])


In [ ]:
arr3.dtype

In [ ]:
import numpy as np
arr1=np.array([5,3,4])
arr2=np.array([1,2,3])
print(np.matmul(arr2,arr1))

In [ ]:
lis1=np.array([[1,2,3],
               [1,2,3]])
lis2=np.array([[0,1,0],
               [1,2,0],
              [1,2,0]])
lis2.shape


In [ ]:
np.matmul(lis1,lis2)

In [ ]:
data=np.genfromtxt('winequality-red.csv',delimiter=';',skip_header=2,usecols=(0,1,2))

In [ ]:
data.shape

In [ ]:
print(data)

In [ ]:
arr3

In [ ]:
arr1*arr2

In [ ]:
arr1


In [ ]:
arr2

In [ ]:
print(np.dot(arr1,arr2))

In [ ]:
dp=data@arr1

In [ ]:
data.shape

In [ ]:
dp.shape

In [ ]:
arr1.shape

In [ ]:
dp
dp.shape

In [ ]:
res=np.concatenate((data, dp.reshape(1598,1)),axis=1)

In [ ]:
res

In [ ]:
res.dtype

In [ ]:
arr=np.array([[1,2,3]])

In [ ]:
arr.shape

In [ ]:
help(np.reshape)


In [ ]:
np.concatenate((arr1,arr2),axis=0)

In [ ]:
arr1.shape

In [ ]:
res.shape

In [ ]:
np.savetxt('result.csv',res,delimiter=',',fmt='%.2f',header='yes,no,why,wow',comments='')

In [ ]:
import numpy as np
newdata=np.genfromtxt('result.txt',delimiter=',',skip_header=1)

In [ ]:
newdata


In [ ]:
np.savetxt('wow.csv',newdata,delimiter=';',fmt='%.1f',header='yes;no;wow;jao',comments='')

In [ ]:
array1=np.array([[1,2],
                 [1,2]])

In [ ]:
array2=np.array([1,2,3,4])

In [ ]:
np.concatenate((array1,array2.reshape(2,2)),axis=1)

In [ ]:
array1.shape

In [ ]:
array2.shape

In [ ]:
array1.shape

In [ ]:
array2.shape

In [ ]:
array2.reshape(2,2)

In [ ]:
array2.shape

In [ ]:
array2.reshape(2,2)+array1

In [ ]:
array2.reshape(1,4)

In [ ]:
array3=np.array([[[[1,2,3],
                  [1,2,3]]],
                 [[[1,2,3],
                  [1,2,3]]]])

In [ ]:
array3.shape

In [ ]:
array4=np.array([1,2,3])

In [ ]:
array3+array4

In [ ]:
array4+array3

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Generate 10,000 random numbers
data = 5+15*np.random.randn(6)
print(data)
# Plot histogram
plt.hist(data, bins=50, density=True, alpha=0.6, color='b')

# Show plot
plt.title("Histogram of randn() values")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()


In [ ]:
np.arange(2,30,2).reshape(7,2,1)

In [ ]:
arr=np.linspace(1,20,10).reshape(2,5)

In [ ]:
import numpy as np

# Create a 3D array with 30 values, reshaped into (2, 3, 5)
arr_3d = np.linspace(1, 30, 30).reshape(2, 3, 5)

# Round to 2 decimal places
rounded_arr_3d = np.round(arr_3d, 2)

print(rounded_arr_3d)


In [ ]:
for matrix in rounded_arr_3d:
    for row in matrix:
        print(["{:.2f}".format(num) for num in row])


In [ ]:
zero=np.zeros((1,1))

In [ ]:
one=np.ones((1,2))

In [ ]:
np.concatenate((zero,one.reshape(2,1)),axis=0)

In [ ]:
daty=np.genfromtxt("nyc_taxis.csv",delimiter=',',dtype=float,skip_header=True)

In [ ]:
print(daty)

#  converting system of linear equactions into metrices

#     -x+3y=7
#     3x+2y=1     


In [4]:
A=np.array([[-1,3],
            [3,2]],dtype=np.dtype(float))
B=np.array([7,1],dtype=np.dtype(float))
print(f"Matrix A={A}")
print(f"Matrix B={B}")


Matrix A=[[-1.  3.]
 [ 3.  2.]]
Matrix B=[7. 1.]


# finding solution for the system 0f linear equations
# using numpy.linalg.solve()

In [12]:
x=np.linalg.solve(A,B)
print(f"x={x}")

x=[-1.  2.]


#  the above given system of linear equations gives a square matrix of 2x2 and a vector of 2x1
# in case of square matrix it is possible to calculate determinant of the matrix 
# and if the determinant is not equal to zero then the matrix is invertible and
#  the solution of the system of linear equations can be found using the formula x=A^(-1)B


In [7]:
#Calculating determinant
det_A=np.linalg.det(A)
print(f"Determinant of A={det_A}")

Determinant of A=-11.000000000000002


Notice that the determinant is non zero as expected


Solving system of linear equations using elemination method

In [13]:
help(np.hstack)

Help on _ArrayFunctionDispatcher in module numpy:

hstack(tup, *, dtype=None, casting='same_kind')
    Stack arrays in sequence horizontally (column wise).

    This is equivalent to concatenation along the second axis, except for 1-D
    arrays where it concatenates along the first axis. Rebuilds arrays divided
    by `hsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    Parameters
    ----------
    tup : sequence of ndarrays
        The arrays must have the same shape along all but the second axis,
        except 1-D arrays which can be any length. In the case of a single
        array_like input, it will be treated as a sequence of arrays; i.e.,
        each element along the zeroth axis is treated as a separate array.

 

In [14]:
A_system=np.concatenate((A,B.reshape(2,1)),axis=1)
print(f"Matrix A_system={A_system}")

Matrix A_system=[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [20]:
print(A_system[1])

[3. 2. 1.]


In [31]:
A_sys_res=A_system.copy()



In [32]:
A_sys_res[1]=3*A_sys_res[0]+A_sys_res[1]
print(f"Matrix A_sys_res={A_sys_res}")

Matrix A_sys_res=[[-1.  3.  7.]
 [ 0. 11. 22.]]


In [33]:
A_sys_res[1]=1/11*A_sys_res[1]
print(f"Matrix A_sys_res={A_sys_res}")

Matrix A_sys_res=[[-1.  3.  7.]
 [ 0.  1.  2.]]
